/* eslint-disable sonarjs/no-duplicate-string */
/* eslint-disable import/prefer-default-export */
// TODO: have script to convert from less variable of antd

export const defaultTheme = {
  blueBase: '#1890ff',
  blue1: '#e6f7ff',
  blue2: '#bae7ff',
  blue3: '#91d5ff',
  blue4: '#69c0ff',
  blue5: '#40a9ff',
  blue6: '#1890ff',
  blue7: '#096dd9',
  blue8: '#0050b3',
  blue9: '#003a8c',
  blue10: '#002766',
  purpleBase: '#722ed1',
  purple1: '#f9f0ff',
  purple2: '#efdbff',
  purple3: '#d3adf7',
  purple4: '#b37feb',
  purple5: '#9254de',
  purple6: '#722ed1',
  purple7: '#531dab',
  purple8: '#391085',
  purple9: '#22075e',
  purple10: '#120338',
  cyanBase: '#13c2c2',
  cyan1: '#e6fffb',
  cyan2: '#b5f5ec',
  cyan3: '#87e8de',
  cyan4: '#5cdbd3',
  cyan5: '#36cfc9',
  cyan6: '#13c2c2',
  cyan7: '#08979c',
  cyan8: '#006d75',
  cyan9: '#00474f',
  cyan10: '#002329',
  greenBase: '#52c41a',
  green1: '#f6ffed',
  green2: '#d9f7be',
  green3: '#b7eb8f',
  green4: '#95de64',
  green5: '#73d13d',
  green6: '#52c41a',
  green7: '#389e0d',
  green8: '#237804',
  green9: '#135200',
  green10: '#092b00',
  magentaBase: '#eb2f96',
  magenta1: '#fff0f6',
  magenta2: '#ffd6e7',
  magenta3: '#ffadd2',
  magenta4: '#ff85c0',
  magenta5: '#f759ab',
  magenta6: '#eb2f96',
  magenta7: '#c41d7f',
  magenta8: '#9e1068',
  magenta9: '#780650',
  magenta10: '#520339',
  pinkBase: '#eb2f96',
  pink1: '#fff0f6',
  pink2: '#ffd6e7',
  pink3: '#ffadd2',
  pink4: '#ff85c0',
  pink5: '#f759ab',
  pink6: '#eb2f96',
  pink7: '#c41d7f',
  pink8: '#9e1068',
  pink9: '#780650',
  pink10: '#520339',
  redBase: '#f5222d',
  red1: '#fff1f0',
  red2: '#ffccc7',
  red3: '#ffa39e',
  red4: '#ff7875',
  red5: '#ff4d4f',
  red6: '#f5222d',
  red7: '#cf1322',
  red8: '#a8071a',
  red9: '#820014',
  red10: '#5c0011',
  orangeBase: '#fa8c16',
  orange1: '#fff7e6',
  orange2: '#ffe7ba',
  orange3: '#ffd591',
  orange4: '#ffc069',
  orange5: '#ffa940',
  orange6: '#fa8c16',
  orange7: '#d46b08',
  orange8: '#ad4e00',
  orange9: '#873800',
  orange10: '#612500',
  yellowBase: '#fadb14',
  yellow1: '#feffe6',
  yellow2: '#ffffb8',
  yellow3: '#fffb8f',
  yellow4: '#fff566',
  yellow5: '#ffec3d',
  yellow6: '#fadb14',
  yellow7: '#d4b106',
  yellow8: '#ad8b00',
  yellow9: '#876800',
  yellow10: '#614700',
  volcanoBase: '#fa541c',
  volcano1: '#fff2e8',
  volcano2: '#ffd8bf',
  volcano3: '#ffbb96',
  volcano4: '#ff9c6e',
  volcano5: '#ff7a45',
  volcano6: '#fa541c',
  volcano7: '#d4380d',
  volcano8: '#ad2102',
  volcano9: '#871400',
  volcano10: '#610b00',
  geekblueBase: '#2f54eb',
  geekblue1: '#f0f5ff',
  geekblue2: '#d6e4ff',
  geekblue3: '#adc6ff',
  geekblue4: '#85a5ff',
  geekblue5: '#597ef7',
  geekblue6: '#2f54eb',
  geekblue7: '#1d39c4',
  geekblue8: '#10239e',
  geekblue9: '#061178',
  geekblue10: '#030852',
  limeBase: '#a0d911',
  lime1: '#fcffe6',
  lime2: '#f4ffb8',
  lime3: '#eaff8f',
  lime4: '#d3f261',
  lime5: '#bae637',
  lime6: '#a0d911',
  lime7: '#7cb305',
  lime8: '#5b8c00',
  lime9: '#3f6600',
  lime10: '#254000',
  goldBase: '#faad14',
  gold1: '#fffbe6',
  gold2: '#fff1b8',
  gold3: '#ffe58f',
  gold4: '#ffd666',
  gold5: '#ffc53d',
  gold6: '#faad14',
  gold7: '#d48806',
  gold8: '#ad6800',
  gold9: '#874d00',
  gold10: '#613400',
  presetColors:
    'pink, magenta, red, volcano, orange, yellow, gold, cyan, lime, green, blue, geekblue, purple',
  theme: 'default',
  antPrefix: 'ant',
  htmlSelector: 'html',
  primaryColor: '#1890ff',
  primaryColorHover: '#40a9ff',
  primaryColorActive: '#096dd9',
  primaryColorOutline: 'rgba(24, 144, 255, 0.2)',
  processingColor: '#1890ff',
  infoColor: '#1890ff',
  infoColorDeprecatedBg: '#e6f7ff',
  infoColorDeprecatedBorder: '#91d5ff',
  successColor: '#52c41a',
  successColorHover: '#73d13d',
  successColorActive: '#389e0d',
  successColorOutline: 'rgba(82, 196, 26, 0.2)',
  successColorDeprecatedBg: '#f6ffed',
  successColorDeprecatedBorder: '#b7eb8f',
  warningColor: '#faad14',
  warningColorHover: '#ffc53d',
  warningColorActive: '#d48806',
  warningColorOutline: 'rgba(250, 173, 20, 0.2)',
  warningColorDeprecatedBg: '#fffbe6',
  warningColorDeprecatedBorder: '#ffe58f',
  errorColor: '#ff4d4f',
  errorColorHover: '#ff7875',
  errorColorActive: '#d9363e',
  errorColorOutline: 'rgba(255, 77, 79, 0.2)',
  errorColorDeprecatedBg: '#fff2f0',
  errorColorDeprecatedBorder: '#ffccc7',
  highlightColor: '#ff4d4f',
  normalColor: '#d9d9d9',
  white: '#fff',
  black: '#000',
  primary1: '#e6f7ff',
  primary2: '#bae7ff',
  primary3: '#91d5ff',
  primary4: '#69c0ff',
  primary5: '#40a9ff',
  primary6: '#1890ff',
  primary7: '#096dd9',
  primary8: '#0050b3',
  primary9: '#003a8c',
  primary10: '#002766',
  bodyBackground: '#fff',
  componentBackground: '#fff',
  popoverBackground: '#fff',
  popoverCustomizeBorderColor: '#f0f0f0',
  fontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  codeFamily: "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
  textColor: 'rgba(0, 0, 0, 0.85)',
  textColorSecondary: 'rgba(0, 0, 0, 0.45)',
  textColorInverse: '#fff',
  iconColor: 'inherit',
  iconColorHover: 'rgba(0, 0, 0, 0.75)',
  headingColor: 'rgba(0, 0, 0, 0.85)',
  textColorDark: 'rgba(255, 255, 255, 0.85)',
  textColorSecondaryDark: 'rgba(255, 255, 255, 0.65)',
  textSelectionBg: '#1890ff',
  fontVariantBase: 'tabular-nums',
  fontFeatureSettingsBase: "'tnum'",
  fontSizeBase: '14px',
  fontSizeLg: '16px',
  fontSizeSm: '12px',
  heading1Size: '38px',
  heading2Size: '30px',
  heading3Size: '24px',
  heading4Size: '20px',
  heading5Size: '16px',
  lineHeightBase: '1.5715',
  borderRadiusBase: '2px',
  borderRadiusSm: '2px',
  paddingLg: '24px',
  paddingMd: '16px',
  paddingSm: '12px',
  paddingXs: '8px',
  paddingXss: '4px',
  controlPaddingHorizontal: '12px',
  controlPaddingHorizontalSm: '8px',
  marginLg: '24px',
  marginMd: '16px',
  marginSm: '12px',
  marginXs: '8px',
  marginXss: '4px',
  heightBase: '32px',
  heightLg: '40px',
  heightSm: '24px',
  itemActiveBg: '#e6f7ff',
  itemHoverBg: '#f5f5f5',
  iconfontCssPrefix: 'anticon',
  linkColor: '#1890ff',
  linkHoverColor: '#40a9ff',
  linkActiveColor: '#096dd9',
  linkDecoration: 'none',
  linkHoverDecoration: 'none',
  linkFocusDecoration: 'none',
  linkFocusOutline: '0',
  easeBaseOut: 'cubic-bezier(0.7, 0.3, 0.1, 1)',
  easeBaseIn: 'cubic-bezier(0.9, 0, 0.3, 0.7)',
  easeOut: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
  easeIn: 'cubic-bezier(0.55, 0.055, 0.675, 0.19)',
  easeInOut: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  easeOutBack: 'cubic-bezier(0.12, 0.4, 0.29, 1.46)',
  easeInBack: 'cubic-bezier(0.71, -0.46, 0.88, 0.6)',
  easeInOutBack: 'cubic-bezier(0.71, -0.46, 0.29, 1.46)',
  easeOutCirc: 'cubic-bezier(0.08, 0.82, 0.17, 1)',
  easeInCirc: 'cubic-bezier(0.6, 0.04, 0.98, 0.34)',
  easeInOutCirc: 'cubic-bezier(0.78, 0.14, 0.15, 0.86)',
  easeOutQuint: 'cubic-bezier(0.23, 1, 0.32, 1)',
  easeInQuint: 'cubic-bezier(0.755, 0.05, 0.855, 0.06)',
  easeInOutQuint: 'cubic-bezier(0.86, 0, 0.07, 1)',
  borderColorBase: '#d9d9d9',
  borderColorSplit: '#f0f0f0',
  borderColorInverse: '#fff',
  borderWidthBase: '1px',
  borderStyleBase: 'solid',
  outlineBlurSize: '0',
  outlineWidth: '2px',
  outlineColor: '#1890ff',
  outlineFade: '20%',
  backgroundColorLight: '#fafafa',
  backgroundColorBase: '#f5f5f5',
  disabledColor: 'rgba(0, 0, 0, 0.25)',
  disabledBg: '#f5f5f5',
  disabledActiveBg: '#e6e6e6',
  disabledColorDark: 'rgba(255, 255, 255, 0.35)',
  shadowColor: 'rgba(0, 0, 0, 0.15)',
  shadowColorInverse: '#fff',
  boxShadowBase:
    '0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
  shadow1Up:
    '0 -6px 16px -8px rgba(0, 0, 0, 0.08), 0 -9px 28px 0 rgba(0, 0, 0, 0.05), 0 -12px 48px 16px rgba(0, 0, 0, 0.03)',
  shadow1Down:
    '0 6px 16px -8px rgba(0, 0, 0, 0.08), 0 9px 28px 0 rgba(0, 0, 0, 0.05), 0 12px 48px 16px rgba(0, 0, 0, 0.03)',
  shadow1Left:
    '-6px 0 16px -8px rgba(0, 0, 0, 0.08), -9px 0 28px 0 rgba(0, 0, 0, 0.05), -12px 0 48px 16px rgba(0, 0, 0, 0.03)',
  shadow1Right:
    '6px 0 16px -8px rgba(0, 0, 0, 0.08), 9px 0 28px 0 rgba(0, 0, 0, 0.05), 12px 0 48px 16px rgba(0, 0, 0, 0.03)',
  shadow2:
    '0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
  btnFontWeight: '400',
  btnBorderRadiusBase: '2px',
  btnBorderRadiusSm: '2px',
  btnBorderWidth: '1px',
  btnBorderStyle: 'solid',
  btnShadow: '0 2px 0 rgba(0, 0, 0, 0.015)',
  btnPrimaryShadow: '0 2px 0 rgba(0, 0, 0, 0.045)',
  btnTextShadow: '0 -1px 0 rgba(0, 0, 0, 0.12)',
  btnPrimaryColor: '#fff',
  btnPrimaryBg: '#1890ff',
  btnDefaultColor: 'rgba(0, 0, 0, 0.85)',
  btnDefaultBg: '#fff',
  btnDefaultBorder: '#d9d9d9',
  btnDangerColor: '#fff',
  btnDangerBg: '#ff4d4f',
  btnDangerBorder: '#ff4d4f',
  btnDisableColor: 'rgba(0, 0, 0, 0.25)',
  btnDisableBg: '#f5f5f5',
  btnDisableBorder: '#d9d9d9',
  btnDefaultGhostColor: '#fff',
  btnDefaultGhostBg: 'transparent',
  btnDefaultGhostBorder: '#fff',
  btnFontSizeLg: '16px',
  btnFontSizeSm: '14px',
  btnPaddingHorizontalBase: '15px',
  btnPaddingHorizontalLg: '15px',
  btnPaddingHorizontalSm: '7px',
  btnHeightBase: '32px',
  btnHeightLg: '40px',
  btnHeightSm: '24px',
  btnLineHeight: '1.5715',
  btnCircleSize: '32px',
  btnCircleSizeLg: '40px',
  btnCircleSizeSm: '24px',
  btnSquareSize: '32px',
  btnSquareSizeLg: '40px',
  btnSquareSizeSm: '24px',
  btnSquareOnlyIconSize: '16px',
  btnSquareOnlyIconSizeSm: '14px',
  btnSquareOnlyIconSizeLg: '18px',
  btnGroupBorder: '#40a9ff',
  btnLinkHoverBg: 'transparent',
  btnTextHoverBg: 'rgba(0, 0, 0, 0.018)',
  checkboxSize: '16px',
  checkboxColor: '#1890ff',
  checkboxCheckColor: '#fff',
  checkboxCheckBg: '#fff',
  checkboxBorderWidth: '1px',
  checkboxBorderRadius: '2px',
  checkboxGroupItemMarginRight: '8px',
  descriptionsBg: '#fafafa',
  descriptionsTitleMarginBottom: '20px',
  descriptionsDefaultPadding: '16px 24px',
  descriptionsMiddlePadding: '12px 24px',
  descriptionsSmallPadding: '8px 16px',
  descriptionsItemPaddingBottom: '16px',
  descriptionsItemTrailingColon: 'true',
  descriptionsItemLabelColonMarginRight: '8px',
  descriptionsItemLabelColonMarginLeft: '2px',
  descriptionsExtraColor: 'rgba(0, 0, 0, 0.85)',
  dividerTextPadding: '1em',
  dividerOrientationMargin: '5%',
  dividerColor: 'rgba(0, 0, 0, 0.06)',
  dividerVerticalGutter: '8px',
  dropdownSelectedColor: '#1890ff',
  dropdownMenuSubmenuDisabledBg: '#fff',
  dropdownSelectedBg: '#e6f7ff',
  emptyFontSize: '14px',
  radioSize: '16px',
  radioTop: '0.2em',
  radioBorderWidth: '1px',
  radioDotSize: '8px',
  radioDotColor: '#1890ff',
  radioDotDisabledColor: 'rgba(0, 0, 0, 0.2)',
  radioSolidCheckedColor: '#fff',
  radioButtonBg: '#fff',
  radioButtonCheckedBg: '#fff',
  radioButtonColor: 'rgba(0, 0, 0, 0.85)',
  radioButtonHoverColor: '#40a9ff',
  radioButtonActiveColor: '#096dd9',
  radioButtonPaddingHorizontal: '15px',
  radioDisabledButtonCheckedBg: '#e6e6e6',
  radioDisabledButtonCheckedColor: 'rgba(0, 0, 0, 0.25)',
  radioWrapperMarginRight: '8px',
  screenXs: '480px',
  screenXsMin: '480px',
  screenSm: '576px',
  screenSmMin: '576px',
  screenMd: '768px',
  screenMdMin: '768px',
  screenLg: '992px',
  screenLgMin: '992px',
  screenXl: '1200px',
  screenXlMin: '1200px',
  screenXxl: '1600px',
  screenXxlMin: '1600px',
  screenXsMax: '575px',
  screenSmMax: '767px',
  screenMdMax: '991px',
  screenLgMax: '1199px',
  screenXlMax: '1599px',
  gridColumns: '24',
  layoutBodyBackground: '#f0f2f5',
  layoutHeaderBackground: '#001529',
  layoutHeaderHeight: '64px',
  layoutHeaderPadding: '0 50px',
  layoutHeaderColor: 'rgba(0, 0, 0, 0.85)',
  layoutFooterPadding: '24px 50px',
  layoutFooterBackground: '#f0f2f5',
  layoutSiderBackground: '#001529',
  layoutTriggerHeight: '48px',
  layoutTriggerBackground: '#002140',
  layoutTriggerColor: '#fff',
  layoutZeroTriggerWidth: '36px',
  layoutZeroTriggerHeight: '42px',
  layoutSiderBackgroundLight: '#fff',
  layoutTriggerBackgroundLight: '#fff',
  layoutTriggerColorLight: 'rgba(0, 0, 0, 0.85)',
  zindexBadge: 'auto',
  zindexTableFixed: '2',
  zindexAffix: '10',
  zindexBackTop: '10',
  zindexPickerPanel: '10',
  zindexPopupClose: '10',
  zindexModal: '1000',
  zindexModalMask: '1000',
  zindexMessage: '1010',
  zindexNotification: '1010',
  zindexPopover: '1030',
  zindexDropdown: '1050',
  zindexPicker: '1050',
  zindexPopoconfirm: '1060',
  zindexTooltip: '1070',
  zindexImage: '1080',
  animationDurationSlow: '0.3s',
  animationDurationBase: '0.2s',
  animationDurationFast: '0.1s',
  collapsePanelBorderRadius: '2px',
  dropdownMenuBg: '#fff',
  dropdownVerticalPadding: '5px',
  dropdownEdgeChildVerticalPadding: '4px',
  dropdownFontSize: '14px',
  dropdownLineHeight: '22px',
  labelRequiredColor: '#ff4d4f',
  labelColor: 'rgba(0, 0, 0, 0.85)',
  formWarningInputBg: '#fff',
  formItemMarginBottom: '24px',
  formItemTrailingColon: 'true',
  formVerticalLabelPadding: '0 0 8px',
  formVerticalLabelMargin: '0',
  formItemLabelFontSize: '14px',
  formItemLabelHeight: '32px',
  formItemLabelColonMarginRight: '8px',
  formItemLabelColonMarginLeft: '2px',
  formErrorInputBg: '#fff',
  inputHeightBase: '32px',
  inputHeightLg: '40px',
  inputHeightSm: '24px',
  inputPaddingHorizontal: '11px',
  inputPaddingHorizontalBase: '11px',
  inputPaddingHorizontalSm: '7px',
  inputPaddingHorizontalLg: '11px',
  inputPaddingVerticalBase: '4px',
  inputPaddingVerticalSm: '0px',
  inputPaddingVerticalLg: '6.5px',
  inputPlaceholderColor: '#bfbfbf',
  inputColor: 'rgba(0, 0, 0, 0.85)',
  inputIconColor: 'rgba(0, 0, 0, 0.85)',
  inputBorderColor: '#d9d9d9',
  inputBg: '#fff',
  inputNumberHoverBorderColor: '#40a9ff',
  inputNumberHandlerActiveBg: '#f4f4f4',
  inputNumberHandlerHoverBg: '#40a9ff',
  inputNumberHandlerBg: '#fff',
  inputNumberHandlerBorderColor: '#d9d9d9',
  inputAddonBg: '#fafafa',
  inputHoverBorderColor: '#40a9ff',
  inputDisabledBg: '#f5f5f5',
  inputOutlineOffset: '0 0',
  inputIconHoverColor: 'rgba(0, 0, 0, 0.85)',
  inputDisabledColor: 'rgba(0, 0, 0, 0.25)',
  mentionsDropdownBg: '#fff',
  mentionsDropdownMenuItemHoverBg: '#fff',
  selectBorderColor: '#d9d9d9',
  selectItemSelectedColor: 'rgba(0, 0, 0, 0.85)',
  selectItemSelectedFontWeight: '600',
  selectDropdownBg: '#fff',
  selectItemSelectedBg: '#e6f7ff',
  selectItemActiveBg: '#f5f5f5',
  selectDropdownVerticalPadding: '5px',
  selectDropdownFontSize: '14px',
  selectDropdownLineHeight: '22px',
  selectDropdownHeight: '32px',
  selectBackground: '#fff',
  selectClearBackground: '#fff',
  selectSelectionItemBg: '#f5f5f5',
  selectSelectionItemBorderColor: '#f0f0f0',
  selectSingleItemHeightLg: '40px',
  selectMultipleItemHeight: '24px',
  selectMultipleItemHeightLg: '32px',
  selectMultipleItemSpacingHalf: '2px',
  selectMultipleDisabledBackground: '#f5f5f5',
  selectMultipleItemDisabledColor: '#bfbfbf',
  selectMultipleItemDisabledBorderColor: '#d9d9d9',
  cascaderBg: '#fff',
  cascaderItemSelectedBg: '#e6f7ff',
  cascaderMenuBg: '#fff',
  cascaderMenuBorderColorSplit: '#f0f0f0',
  cascaderDropdownVerticalPadding: '5px',
  cascaderDropdownEdgeChildVerticalPadding: '4px',
  cascaderDropdownFontSize: '14px',
  cascaderDropdownLineHeight: '22px',
  anchorBg: 'transparent',
  anchorBorderColor: '#f0f0f0',
  anchorLinkTop: '7px',
  anchorLinkLeft: '16px',
  anchorLinkPadding: '7px 0 7px 16px',
  tooltipMaxWidth: '250px',
  tooltipColor: '#fff',
  tooltipBg: 'rgba(0, 0, 0, 0.75)',
  tooltipArrowWidth: '11.3137085px',
  tooltipDistance: '14.3137085px',
  tooltipArrowColor: 'rgba(0, 0, 0, 0.75)',
  popoverBg: '#fff',
  popoverColor: 'rgba(0, 0, 0, 0.85)',
  popoverMinWidth: '177px',
  popoverMinHeight: '32px',
  popoverArrowWidth: '11.3137085px',
  popoverArrowColor: '#fff',
  popoverArrowOuterColor: '#fff',
  popoverDistance: '15.3137085px',
  popoverPaddingHorizontal: '16px',
  modalHeaderPaddingVertical: '16px',
  modalHeaderPaddingHorizontal: '24px',
  modalBodyPadding: '24px',
  modalHeaderBg: '#fff',
  modalHeaderPadding: '16px 24px',
  modalHeaderBorderWidth: '1px',
  modalHeaderBorderStyle: 'solid',
  modalHeaderTitleLineHeight: '22px',
  modalHeaderTitleFontSize: '16px',
  modalHeaderBorderColorSplit: '#f0f0f0',
  modalHeaderCloseSize: '56px',
  modalContentBg: '#fff',
  modalHeadingColor: 'rgba(0, 0, 0, 0.85)',
  modalCloseColor: 'rgba(0, 0, 0, 0.45)',
  modalFooterBg: 'transparent',
  modalFooterBorderColorSplit: '#f0f0f0',
  modalFooterBorderStyle: 'solid',
  modalFooterPaddingVertical: '10px',
  modalFooterPaddingHorizontal: '16px',
  modalFooterBorderWidth: '1px',
  modalMaskBg: 'rgba(0, 0, 0, 0.45)',
  modalConfirmBodyPadding: '32px 32px 24px',
  modalConfirmTitleFontSize: '16px',
  progressDefaultColor: '#1890ff',
  progressRemainingColor: '#f5f5f5',
  progressInfoTextColor: 'rgba(0, 0, 0, 0.85)',
  progressRadius: '100px',
  progressStepsItemBg: '#f3f3f3',
  progressTextFontSize: '1em',
  progressTextColor: 'rgba(0, 0, 0, 0.85)',
  progressCircleTextFontSize: '1em',
  menuInlineToplevelItemHeight: '40px',
  menuItemHeight: '40px',
  menuItemGroupHeight: '1.5715',
  menuCollapsedWidth: '80px',
  menuBg: '#fff',
  menuPopupBg: '#fff',
  menuItemColor: 'rgba(0, 0, 0, 0.85)',
  menuInlineSubmenuBg: '#fafafa',
  menuHighlightColor: '#1890ff',
  menuHighlightDangerColor: '#ff4d4f',
  menuItemActiveBg: '#e6f7ff',
  menuItemActiveDangerBg: '#fff1f0',
  menuItemActiveBorderWidth: '3px',
  menuItemGroupTitleColor: 'rgba(0, 0, 0, 0.45)',
  menuItemVerticalMargin: '4px',
  menuItemFontSize: '14px',
  menuItemBoundaryMargin: '8px',
  menuItemPaddingHorizontal: '20px',
  menuItemPadding: '0 20px',
  menuHorizontalLineHeight: '46px',
  menuIconMarginRight: '10px',
  menuIconSize: '14px',
  menuIconSizeLg: '16px',
  menuItemGroupTitleFontSize: '14px',
  menuDarkColor: 'rgba(255, 255, 255, 0.65)',
  menuDarkDangerColor: '#ff4d4f',
  menuDarkBg: '#001529',
  menuDarkArrowColor: '#fff',
  menuDarkInlineSubmenuBg: '#000c17',
  menuDarkHighlightColor: '#fff',
  menuDarkItemActiveBg: '#1890ff',
  menuDarkItemActiveDangerBg: '#ff4d4f',
  menuDarkSelectedItemIconColor: '#fff',
  menuDarkSelectedItemTextColor: '#fff',
  menuDarkItemHoverBg: 'transparent',
  spinDotSizeSm: '14px',
  spinDotSize: '20px',
  spinDotSizeLg: '32px',
  tableBg: '#fff',
  tableHeaderBg: '#fafafa',
  tableHeaderColor: 'rgba(0, 0, 0, 0.85)',
  tableHeaderSortBg: '#f5f5f5',
  tableBodySortBg: '#fafafa',
  tableRowHoverBg: '#fafafa',
  tableSelectedRowColor: 'inherit',
  tableSelectedRowBg: '#e6f7ff',
  tableBodySelectedSortBg: '#e6f7ff',
  tableSelectedRowHoverBg: '#dcf4ff',
  tableExpandedRowBg: '#fbfbfb',
  tablePaddingVertical: '16px',
  tablePaddingHorizontal: '16px',
  tablePaddingVerticalMd: '12px',
  tablePaddingHorizontalMd: '8px',
  tablePaddingVerticalSm: '8px',
  tablePaddingHorizontalSm: '8px',
  tableBorderColor: '#f0f0f0',
  tableBorderRadiusBase: '2px',
  tableFooterBg: '#fafafa',
  tableFooterColor: 'rgba(0, 0, 0, 0.85)',
  tableHeaderBgSm: '#fafafa',
  tableFontSize: '14px',
  tableFontSizeMd: '14px',
  tableFontSizeSm: '14px',
  tableHeaderCellSplitColor: 'rgba(0, 0, 0, 0.06)',
  tableHeaderSortActiveBg: 'rgba(0, 0, 0, 0.04)',
  tableFixedHeaderSortActiveBg: '#f5f5f5',
  tableHeaderFilterActiveBg: 'rgba(0, 0, 0, 0.04)',
  tableFilterBtnsBg: 'inherit',
  tableFilterDropdownBg: '#fff',
  tableExpandIconBg: '#fff',
  tableSelectionColumnWidth: '32px',
  tableStickyScrollBarBg: 'rgba(0, 0, 0, 0.35)',
  tableStickyScrollBarRadius: '4px',
  tagDefaultBg: '#fafafa',
  tagDefaultColor: 'rgba(0, 0, 0, 0.85)',
  tagFontSize: '12px',
  tagLineHeight: '20px',
  pickerBg: '#fff',
  pickerBasicCellHoverColor: '#f5f5f5',
  pickerBasicCellActiveWithRangeColor: '#e6f7ff',
  pickerBasicCellHoverWithRangeColor: '#cbe6ff',
  pickerBasicCellDisabledBg: 'rgba(0, 0, 0, 0.04)',
  pickerBorderColor: '#f0f0f0',
  pickerDateHoverRangeBorderColor: '#7ec1ff',
  pickerDateHoverRangeColor: '#cbe6ff',
  pickerTimePanelColumnWidth: '56px',
  pickerTimePanelColumnHeight: '224px',
  pickerTimePanelCellHeight: '28px',
  pickerPanelCellHeight: '24px',
  pickerPanelCellWidth: '36px',
  pickerTextHeight: '40px',
  pickerPanelWithoutTimeCellHeight: '66px',
  calendarBg: '#fff',
  calendarInputBg: '#fff',
  calendarBorderColor: '#fff',
  calendarItemActiveBg: '#e6f7ff',
  calendarColumnActiveBg: 'rgba(230, 247, 255, 0.2)',
  calendarFullBg: '#fff',
  calendarFullPanelBg: '#fff',
  carouselDotWidth: '16px',
  carouselDotHeight: '3px',
  carouselDotActiveWidth: '24px',
  badgeHeight: '20px',
  badgeHeightSm: '14px',
  badgeDotSize: '6px',
  badgeFontSize: '12px',
  badgeFontSizeSm: '12px',
  badgeFontWeight: 'normal',
  badgeStatusSize: '6px',
  badgeTextColor: '#fff',
  badgeColor: '#ff4d4f',
  rateStarColor: '#fadb14',
  rateStarBg: '#f0f0f0',
  rateStarSize: '20px',
  rateStarHoverScale: 'scale(1.1)',
  cardHeadColor: 'rgba(0, 0, 0, 0.85)',
  cardHeadBackground: 'transparent',
  cardHeadFontSize: '16px',
  cardHeadFontSizeSm: '14px',
  cardHeadPadding: '16px',
  cardHeadPaddingSm: '8px',
  cardHeadHeight: '48px',
  cardHeadHeightSm: '36px',
  cardInnerHeadPadding: '12px',
  cardPaddingBase: '24px',
  cardPaddingBaseSm: '12px',
  cardActionsBackground: '#fff',
  cardActionsLiMargin: '12px 0',
  cardSkeletonBg: '#cfd8dc',
  cardBackground: '#fff',
  cardShadow:
    '0 1px 2px -2px rgba(0, 0, 0, 0.16), 0 3px 6px 0 rgba(0, 0, 0, 0.12), 0 5px 12px 4px rgba(0, 0, 0, 0.09)',
  cardRadius: '2px',
  cardHeadTabsMarginBottom: '-17px',
  cardHeadExtraColor: 'rgba(0, 0, 0, 0.85)',
  commentBg: 'inherit',
  commentPaddingBase: '16px 0',
  commentNestIndent: '44px',
  commentFontSizeBase: '14px',
  commentFontSizeSm: '12px',
  commentAuthorNameColor: 'rgba(0, 0, 0, 0.45)',
  commentAuthorTimeColor: '#ccc',
  commentActionColor: 'rgba(0, 0, 0, 0.45)',
  commentActionHoverColor: '#595959',
  commentActionsMarginBottom: 'inherit',
  commentActionsMarginTop: '12px',
  commentContentDetailPMarginBottom: 'inherit',
  tabsCardHeadBackground: '#fafafa',
  tabsCardHeight: '40px',
  tabsCardActiveColor: '#1890ff',
  tabsCardHorizontalPadding: '8px 16px',
  tabsCardHorizontalPaddingSm: '6px 16px',
  tabsCardHorizontalPaddingLg: '7px 16px 6px',
  tabsTitleFontSize: '14px',
  tabsTitleFontSizeLg: '16px',
  tabsTitleFontSizeSm: '14px',
  tabsInkBarColor: '#1890ff',
  tabsBarMargin: '0 0 16px 0',
  tabsHorizontalGutter: '32px',
  tabsHorizontalMargin: '0 0 0 32px',
  tabsHorizontalMarginRtl: '0 0 0 32px',
  tabsHorizontalPadding: '12px 0',
  tabsHorizontalPaddingLg: '16px 0',
  tabsHorizontalPaddingSm: '8px 0',
  tabsVerticalPadding: '8px 24px',
  tabsVerticalMargin: '16px 0 0 0',
  tabsScrollingSize: '32px',
  tabsHighlightColor: '#1890ff',
  tabsHoverColor: '#40a9ff',
  tabsActiveColor: '#096dd9',
  tabsCardGutter: '2px',
  tabsCardTabActiveBorderTop: '2px solid transparent',
  backTopColor: '#fff',
  backTopBg: 'rgba(0, 0, 0, 0.45)',
  backTopHoverBg: 'rgba(0, 0, 0, 0.85)',
  avatarSizeBase: '32px',
  avatarSizeLg: '40px',
  avatarSizeSm: '24px',
  avatarFontSizeBase: '18px',
  avatarFontSizeLg: '24px',
  avatarFontSizeSm: '14px',
  avatarBg: '#ccc',
  avatarColor: '#fff',
  avatarBorderRadius: '2px',
  avatarGroupOverlapping: '-8px',
  avatarGroupSpace: '3px',
  avatarGroupBorderColor: '#fff',
  switchHeight: '22px',
  switchSmHeight: '16px',
  switchMinWidth: '44px',
  switchSmMinWidth: '28px',
  switchDisabledOpacity: '0.4',
  switchColor: '#1890ff',
  switchBg: '#fff',
  switchShadowColor: 'rgba(0, 35, 11, 0.2)',
  switchPadding: '2px',
  switchInnerMarginMin: '7px',
  switchInnerMarginMax: '25px',
  switchSmInnerMarginMin: '5px',
  switchSmInnerMarginMax: '18px',
  paginationItemBg: '#fff',
  paginationItemSize: '32px',
  paginationItemSizeSm: '24px',
  paginationFontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  paginationFontWeightActive: '500',
  paginationItemBgActive: '#fff',
  paginationItemLinkBg: '#fff',
  paginationItemDisabledColorActive: 'rgba(0, 0, 0, 0.25)',
  paginationItemDisabledBgActive: '#e6e6e6',
  paginationItemInputBg: '#fff',
  paginationMiniOptionsSizeChangerTop: '0px',
  pageHeaderPadding: '24px',
  pageHeaderPaddingVertical: '16px',
  pageHeaderPaddingBreadcrumb: '12px',
  pageHeaderContentPaddingVertical: '12px',
  pageHeaderBackColor: '#000',
  pageHeaderGhostBg: 'inherit',
  pageHeaderHeadingTitle: '20px',
  pageHeaderHeadingSubTitle: '14px',
  pageHeaderTabsTabFontSize: '16px',
  breadcrumbBaseColor: 'rgba(0, 0, 0, 0.45)',
  breadcrumbLastItemColor: 'rgba(0, 0, 0, 0.85)',
  breadcrumbFontSize: '14px',
  breadcrumbIconFontSize: '14px',
  breadcrumbLinkColor: 'rgba(0, 0, 0, 0.45)',
  breadcrumbLinkColorHover: '#40a9ff',
  breadcrumbSeparatorColor: 'rgba(0, 0, 0, 0.45)',
  breadcrumbSeparatorMargin: '0 8px',
  sliderMargin: '10px 6px 10px',
  sliderRailBackgroundColor: '#f5f5f5',
  sliderRailBackgroundColorHover: '#e1e1e1',
  sliderTrackBackgroundColor: '#91d5ff',
  sliderTrackBackgroundColorHover: '#69c0ff',
  sliderHandleBorderWidth: '2px',
  sliderHandleBackgroundColor: '#fff',
  sliderHandleColor: '#91d5ff',
  sliderHandleColorHover: '#69c0ff',
  sliderHandleColorFocus: '#46a6ff',
  sliderHandleColorFocusShadow: 'rgba(24, 144, 255, 0.12)',
  sliderHandleColorTooltipOpen: '#1890ff',
  sliderHandleSize: '14px',
  sliderHandleMarginTop: '-5px',
  sliderHandleShadow: '0',
  sliderDotBorderColor: '#f0f0f0',
  sliderDotBorderColorActive: '#8cc8ff',
  sliderDisabledColor: 'rgba(0, 0, 0, 0.25)',
  sliderDisabledBackgroundColor: '#fff',
  treeBg: '#fff',
  treeTitleHeight: '24px',
  treeChildPadding: '18px',
  treeDirectorySelectedColor: '#fff',
  treeDirectorySelectedBg: '#1890ff',
  treeNodeHoverBg: '#f5f5f5',
  treeNodeSelectedBg: '#bae7ff',
  collapseHeaderPadding: '12px 16px',
  collapseHeaderPaddingExtra: '40px',
  collapseHeaderBg: '#fafafa',
  collapseContentPadding: '16px',
  collapseContentBg: '#fff',
  collapseHeaderArrowLeft: '16px',
  skeletonColor: 'rgba(190, 190, 190, 0.2)',
  skeletonToColor: 'rgba(129, 129, 129, 0.24)',
  skeletonParagraphMarginTop: '28px',
  skeletonParagraphLiMarginTop: '16px',
  skeletonParagraphLiHeight: '16px',
  skeletonTitleHeight: '16px',
  skeletonTitleParagraphMarginTop: '24px',
  transferHeaderHeight: '40px',
  transferItemHeight: '32px',
  transferDisabledBg: '#f5f5f5',
  transferListHeight: '200px',
  transferItemHoverBg: '#f5f5f5',
  transferItemSelectedHoverBg: '#dcf4ff',
  transferItemPaddingVertical: '6px',
  transferListSearchIconTop: '12px',
  messageNoticeContentPadding: '10px 16px',
  messageNoticeContentBg: '#fff',
  waveAnimationWidth: '6px',
  alertSuccessBorderColor: '#b7eb8f',
  alertSuccessBgColor: '#f6ffed',
  alertSuccessIconColor: '#52c41a',
  alertInfoBorderColor: '#91d5ff',
  alertInfoBgColor: '#e6f7ff',
  alertInfoIconColor: '#1890ff',
  alertWarningBorderColor: '#ffe58f',
  alertWarningBgColor: '#fffbe6',
  alertWarningIconColor: '#faad14',
  alertErrorBorderColor: '#ffccc7',
  alertErrorBgColor: '#fff2f0',
  alertErrorIconColor: '#ff4d4f',
  alertMessageColor: 'rgba(0, 0, 0, 0.85)',
  alertTextColor: 'rgba(0, 0, 0, 0.85)',
  alertCloseColor: 'rgba(0, 0, 0, 0.45)',
  alertCloseHoverColor: 'rgba(0, 0, 0, 0.75)',
  alertNoIconPaddingVertical: '8px',
  alertWithDescriptionNoIconPaddingVertical: '15px',
  alertWithDescriptionPaddingVertical: '15px',
  alertWithDescriptionPadding: '15px 15px 15px 24px',
  alertIconTop: '12.0005px',
  alertWithDescriptionIconSize: '24px',
  listHeaderBackground: 'transparent',
  listFooterBackground: 'transparent',
  listEmptyTextPadding: '16px',
  listItemPadding: '12px 0',
  listItemPaddingSm: '8px 16px',
  listItemPaddingLg: '16px 24px',
  listItemMetaMarginBottom: '16px',
  listItemMetaAvatarMarginRight: '16px',
  listItemMetaTitleMarginBottom: '12px',
  listCustomizeCardBg: '#fff',
  listItemMetaDescriptionFontSize: '14px',
  statisticTitleFontSize: '14px',
  statisticContentFontSize: '24px',
  statisticUnitFontSize: '24px',
  statisticFontFamily:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
  drawerHeaderPadding: '16px 24px',
  drawerBodyPadding: '24px',
  drawerBg: '#fff',
  drawerFooterPaddingVertical: '10px',
  drawerFooterPaddingHorizontal: '16px',
  drawerHeaderCloseSize: '56px',
  drawerTitleFontSize: '16px',
  drawerTitleLineHeight: '22px',
  timelineWidth: '2px',
  timelineColor: '#f0f0f0',
  timelineDotBorderWidth: '2px',
  timelineDotColor: '#1890ff',
  timelineDotBg: '#fff',
  timelineItemPaddingBottom: '20px',
  typographyTitleFontWeight: '600',
  typographyTitleMarginTop: '1.2em',
  typographyTitleMarginBottom: '0.5em',
  uploadActionsColor: 'rgba(0, 0, 0, 0.45)',
  processTailColor: '#f0f0f0',
  stepsNavArrowColor: 'rgba(0, 0, 0, 0.25)',
  stepsBackground: '#fff',
  stepsIconSize: '32px',
  stepsIconCustomSize: '32px',
  stepsIconCustomTop: '0px',
  stepsIconCustomFontSize: '24px',
  stepsIconTop: '-0.5px',
  stepsIconFontSize: '16px',
  stepsIconMargin: '0 8px 0 0',
  stepsTitleLineHeight: '32px',
  stepsSmallIconSize: '24px',
  stepsSmallIconMargin: '0 8px 0 0',
  stepsDotSize: '8px',
  stepsDotTop: '2px',
  stepsCurrentDotSize: '10px',
  stepsDescriptionMaxWidth: '140px',
  stepsNavContentMaxWidth: 'auto',
  stepsVerticalIconWidth: '16px',
  stepsVerticalTailWidth: '16px',
  stepsVerticalTailWidthSm: '12px',
  notificationBg: '#fff',
  notificationPaddingVertical: '16px',
  notificationPaddingHorizontal: '24px',
  resultTitleFontSize: '24px',
  resultSubtitleFontSize: '14px',
  resultIconFontSize: '72px',
  resultExtraMargin: '24px 0 0 0',
  imageSizeBase: '48px',
  imageFontSizeBase: '24px',
  imageBg: '#f5f5f5',
  imageColor: '#fff',
  imageMaskFontSize: '16px',
  imagePreviewOperationSize: '18px',
  imagePreviewOperationColor: 'rgba(255, 255, 255, 0.85)',
  imagePreviewOperationDisabledColor: 'rgba(255, 255, 255, 0.25)'
}
