# name: Jitera Web UI package

# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 17
#       - name: Setup yarn
#         run: npm install -g yarn
#       - run: yarn install
#       - run: yarn test
#   publish-gpr:
#     needs: build
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: read
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 17
#           registry-url: https://registry.npmjs.org/
#       - name: Generate npmrc
#         run: |
#           echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
#           echo "registry=https://registry.npmjs.org/" >> .npmrc
#           echo "always-auth=true" >> .npmrc
#       - run: yarn install
#       - run: yarn publish --access public
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   release:
#     needs: publish-gpr
#     runs-on: ubuntu-latest
#     steps:
#       - uses: marvinpinto/action-automatic-releases@latest
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           prerelease: false